test commit to check permissions
muly/product-track pull request #1
Opened 2023-04-03 14:46 UTC by Rohithknaidu

2023-04-14 22:09 UTC, muly requested changes
please also update the PR title, and cover the missing items

2023-04-20 13:47 UTC, muly requested changes
please make the changes per the review comments and then we can take another look at the code and review again.

2023-04-20 13:47 UTC, muly commented on main.go
> +func notify(i input)(bool,error){
lets rename this to `shouldNotify`

2023-04-20 13:47 UTC, muly commented on main.go
> +	price string
change the datatype to `float64`

2023-04-20 13:47 UTC, muly commented on main.go
> +	 availability string
lets change the datatype to `bool`

2023-04-20 13:47 UTC, muly commented on main.go
> +		p.price = h.Text
convert `h.Text` from string to float64 before saving it to `p.price`

2023-04-20 13:47 UTC, muly commented on main.go
> +		p.availability = h.Text
derive the bool value based on the `h.Text` before saving to `p.availability`

2023-04-20 17:55 UTC, Rohithknaidu commented on main.go
> +		p.price = h.Text
these changes are done but the output is not correct

2023-04-20 18:18 UTC, Rohithknaidu commented on main.go
> +		p.price = h.Text
Strconv.Atoi:praising "1899" : invalid syntax

2023-04-22 03:00 UTC, muly requested changes

2023-04-22 03:00 UTC, muly commented on main.go
> +		p.price = h.Text
here is the example of how to use `strconv.Atoi()`
https://go.dev/play/p/rt2eAp3xS4O

the code that you have looks complex, we should try to simplify using `Atoi()` if possible. if it has to stay that complex, can you move that into a function, so that we can write unit tests to make sure it is working as expected.

2023-04-22 05:32 UTC, Rohithknaidu commented
it is not possible using Atoi( ) because we have "1,899" .we can not convert "," into integer.

2023-04-22 05:38 UTC, Rohithknaidu commented on main.go
> +		fmt.Println("error occurred ", err)
no it is not doing like that i've observed that.

2023-04-22 20:05 UTC, muly requested changes

2023-04-22 20:05 UTC, muly commented on main.go
> +func checkAvailability(s string) bool {
simplify the Hurry scenario using regexp

2023-04-22 20:05 UTC, muly commented on main.go
> +	for i = 0; i < len(price); i++ {
replace comma and then parseFloat instead of this logic.

2023-04-22 20:05 UTC, muly commented on main.go
> +
remove empty line at the start of the function

2023-04-29 04:39 UTC, muly commented on main.go
> +		fmt.Println("error occurred while parsing value", err)
pls remove this print statement.

2023-04-29 05:26 UTC, Rohithknaidu commented on main.go
> +		fmt.Println("error occurred while parsing value", err)
done sir

2023-05-13 13:27 UTC, muly approved these changes

2023-05-13 13:27 UTC, merged