chrome extension
muly/product-track pull request #15
Opened 2023-06-27 15:08 UTC by Rohithknaidu

2023-06-29 02:42 UTC, muly requested changes

2023-06-29 02:42 UTC, muly commented on chrome-exten/manifest.json
> +    "permissions":["activeTab","tabs"]
- [ ] do we need `tabs` permission aswell?
- [ ] update `name` and `description` fields

2023-06-29 02:42 UTC, muly commented on chrome-exten/popup.js
> +          fetch(`https://smuly-test-ground.ue.r.appspot.com/track/price`, {
save the common part of the URL (i.e. `https://smuly-test-ground.ue.r.appspot.com`) in a variable and use it here. so that if we need to change the API URL (to localhost or some other place), it will be easy.

2023-06-29 02:42 UTC, muly commented on chrome-exten/popup.js
> +                  alert('Successful') ;
after `Successful` alert is closed, the main chrome extension popup is still open. is there a way to close the chrome extension popup after the submit button is clicked?

2023-06-29 05:20 UTC, Rohithknaidu commented on chrome-exten/manifest.json
> +    "permissions":["activeTab","tabs"]
i think there is no need of tabs permission so i removed it
and updated the  name and description

2023-06-29 05:21 UTC, Rohithknaidu commented on chrome-exten/popup.js
> +          fetch(`https://smuly-test-ground.ue.r.appspot.com/track/price`, {
done sir

2023-06-29 07:35 UTC, Rohithknaidu commented on chrome-exten/popup.js
> +                  alert('Successful') ;
the issue is resolved sir

2023-06-30 03:55 UTC, muly requested changes

2023-06-30 03:55 UTC, muly commented on chrome-exten/manifest.json
> +    "permissions":["activeTab","tabs"]
looks like the `tabs` permission is still there.

2023-06-30 03:55 UTC, muly commented on chrome-exten/manifest.json
> +
cleanup the empty lines

2023-06-30 03:55 UTC, muly commented on chrome-exten/popup.js
> +                  alert('Successful') ;
looks like `window.close();` is not allowing the api call to be competed. but if I comment that line out, the record is successfully saving to the database. I think window closing action should wait for the API call to be completed.

2023-06-30 08:59 UTC, Rohithknaidu commented on chrome-exten/popup.js
> +                  alert('Successful') ;
the data is storing to gcp sir

2023-07-01 18:19 UTC, muly approved these changes

2023-07-01 18:19 UTC, merged