email_notification
muly/product-track pull request #18
Opened 2023-07-06 17:31 UTC by Rohithknaidu

2023-07-07 03:53 UTC, muly requested changes

2023-07-07 03:53 UTC, muly commented on email.go
> +	m.SetHeader("Subject", "Availability update Notification")
format the code

2023-07-07 03:53 UTC, muly commented on email.go
> +	if t.TypeOfRequest=="AVAILABILITY"{
replace the request type with constants.

2023-07-07 03:53 UTC, muly commented on email.go
> +func notify(t trackInput) error {
let's separate the email preparation from the actual send email part.

2023-07-07 03:53 UTC, muly commented on email.go
> +	d := mail.NewDialer("smtp.gmail.com", 587, "smulytestground@gmail.com", password)
let's make the dialer object package level, like the `firestoreClient` object, and add a `init...()` function.

2023-07-07 13:58 UTC, Rohithknaidu commented on email.go
> +	d := mail.NewDialer("smtp.gmail.com", 587, "smulytestground@gmail.com", password)
i didn't understand it sir

2023-07-08 03:36 UTC, muly requested changes

2023-07-08 03:36 UTC, muly commented on email.go
> +var emailclient *mail.Dialer
use camel case

2023-07-08 03:36 UTC, muly commented on email.go
> +
empty space

2023-07-08 03:36 UTC, muly commented on email.go
> +
empty space

2023-07-08 03:36 UTC, muly commented on email.go
> +func requesttype(*mail.Message) {
need a better name for the function. also please add a comment before the function code describing the purpose of the function. to this and all the functions

2023-07-08 03:36 UTC, muly commented on email.go
> +	if err := emailclient.DialAndSend(m); err != nil {
the email will be sent with empty subject and body

2023-07-08 03:36 UTC, muly commented on util.go
> +	requesttype(&mail.Message{})
mock notification log is no longer necessary

2023-07-08 03:36 UTC, muly commented on email.go
> +	var t trackInput
t is empty

2023-07-08 09:28 UTC, Rohithknaidu commented on email.go
> +func requesttype(*mail.Message) {
i tried

2023-07-21 04:01 UTC, muly approved these changes

2023-07-21 04:01 UTC, merged