issues
muly/product-track pull request #49
Opened 2023-11-30 10:49 UTC by Rohithknaidu

2023-12-01 21:53 UTC, muly commented on email.go
> +	log.Println("error due to path in email.go")
why this log?

2023-12-01 21:54 UTC, muly requested changes

2023-12-01 21:54 UTC, muly commented on api.go
> +	t.TypeOfRequest=requestTypeAvailability
good catch.

2023-12-02 19:01 UTC, Rohithknaidu commented on email.go
> +	log.Println("error due to path in email.go")
sorry  sir.what i actually want to know is if i am not getting logo  i want to print that error. for that i should have done something else.

2023-12-09 04:09 UTC, muly approved these changes

2023-12-09 04:09 UTC, merged